spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/companies-qa
    username: debuggeandoideas-qa
    password: KJHAS54AHJG
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
