spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companies-prod
    username: debuggeandoideas-prod
    password: KJHASUIHDAS3521
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
